---
- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Install development packages
      apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - '{{ development_deb_packages }}'
      become: yes
      when: ansible_distribution == 'Ubuntu'
      tags:
        - deb

    - block:
      - name: Install pip
        easy_install:
          name: pip
          state: latest

      - name: Install packages from pip
        pip:
          name: '{{ item }}'
          state: latest
          executable: pip2
        with_items:
          - '{{ pip_packages }}'
      become: yes
      tags: pip

    - block:
      - name: Set no doc for gems
        lineinfile:
          dest: '/etc/gemrc'
          line: 'gem: --no-rdoc --no-ri'
          create: yes
        become: yes

      - name: Install gems
        gem:
          executable: ~/.rbenv/shims/gem
          name: '{{ item }}'
          state: latest
          user_install: no
        # become: yes # no for rbenv
        ignore_errors: yes
        with_items:
          - '{{ ruby_gems }}'
      tags:
        - ruby
        - gem

    - name: Set git configuration
      git_config:
        scope: global
        name: '{{ item.name }}'
        value: '{{ item.value }}'
      with_items:
        - '{{ git_configs }}'
      tags: git

  roles:
    - { role: rbenv, tags: ruby, become: yes }
    - { role: docker, tags: docker, become: yes }
    - { role: sublime3, tags: sublime3 }
