- name: rbenv
  src: https://github.com/zzet/ansible-rbenv-role
  version: 3.3.3

- name: docker
  src: https://github.com/angstwad/docker.ubuntu
  version: v3.3.2

- name: terminator
  src: https://github.com/vterdunov/ansible-terminator

- name: sublime3
  src: https://github.com/vterdunov/ansible-sublime3
